$(document).ready(function(){
$('.slide-carousal').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    slideBy:1,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})
});